chain = "arbitrum"
source = "rpc"
pool_address = "0xc31e54c7a869b9fcbecc14363cf510d1c41fa443"
save_path = "./data"


[rpc]
end_point="https://arb-mainnet-public.unifra.io"
# auth_string = "Basic Y3J0Yzo3NKY3TjY" # optional, used to add auth for some private node
# proxy = "http://localhost:8080" # optional
start_height = 82583468 # start height
end_height = 82952921 # end height
batch_size = 500 # query 500 blocks each time, if the pool is busy,  decrease this number.